# Generated by Django 6.1.2 on 2026-10-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='my-first-django-post', unique=True),
            preserve_default=False,
        ),
    ]
